# Generated by Django 3.2.7 on 2021-09-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article_catagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, auto_now_add=True)),
                ('img', models.ImageField(upload_to='Img/News')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, auto_now_add=True)),
                ('img', models.ImageField(upload_to='Img/Article')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('catagories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article_catagories')),
            ],
        ),
    ]
